DROP TABLE IF EXISTS categories, users, locations, events, requests, compilations, compilation_event;

CREATE TABLE categories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null unique
);

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) not null unique,
    name varchar(250) not null
);

CREATE TABLE locations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat float,
    lon float
);

CREATE TABLE events (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar,
    category_id int references categories(id),
    created_on timestamp without time zone,
    description varchar,
    event_date timestamp without time zone,
    initiator_id int references users(id),
    location_id int references locations(id),
    paid boolean,
    participant_limit int,
    published_on timestamp without time zone,
    request_moderation boolean,
    state varchar,
    title varchar
);

CREATE TABLE requests (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int references events(id),
    initiator_id int references users(id),
    status varchar,
    created timestamp without time zone
);

CREATE TABLE compilations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title varchar
);

CREATE TABLE compilation_event (
    event_id int references events(id),
    compilation_id int references compilations(id)
);