DROP TABLE IF EXISTS categories, users;

CREATE TABLE categories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) not null
);

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) not null unique,
    name varchar(250) not null
);