version: '3.1'

services:
  stats-server:

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5438:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

    ewm-service:
      ports:
        - "8080:8080"

    ewm-db:
      image: postgres:14-alpine
