version: '3.1'

services:
  stats-server:
    build: ./stats/stats-server
    #  "зависит от",
    depends_on:
      - stats-db
    # переменные окружения
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5438:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
   build: ./stats/stats-server
   #  "зависит от",
   depends_on:
     - ewm-db
   # переменные окружения
   environment:
     - DB_NAME=main
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
     - DB_HOST=ewm-db
     - DB_PORT=5432
   ports:
     - "8080:8080"


  ewm-db:
    image: postgres:14-alpine
    ports:
    - "5437:5432"
    volumes:
    - /var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=main
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - DB_PORT=5436
