DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(30) not null,
    uri varchar(100) not null,
    ip varchar(30) not null,
    moment timestamp without time zone
);